version: "3.8"

services:

  dev-kitchen:
    build:
      context: .
      dockerfile: dockerfiles/kitchen.Dockerfile
      target: dev-kitchen
    image: dev-kitchen:latest
    container_name: dev-kitchen-container
    ports:
      - 80:80
      - 81:81
      - 8443:8443
      - 8888:8888
    volumes:
      - $HOME/.aws:/root/.aws
    restart: unless-stopped
    command: bash -c "
      jupyter lab --ip=0.0.0.0 --allow-root --no-browser
      & hypercorn server.server:app --bind 0.0.0.0:81
      & streamlit run window_display/custom_display.py --server.port 80
      & code-server --bind-addr 0.0.0.0:8443 --auth none --disable-telemetry --cert
      "

  base-kitchen:
    build:
      context: .
      dockerfile: dockerfiles/kitchen.Dockerfile
      target: base-kitchen
    image: base-kitchen:latest
    container_name: base-kitchen-container
    volumes:
      - $HOME/.aws:/root/.aws
    command: python -m head_chef.head_chef
