version: "3.8"

services:

  kitchen:
    build:
      context: .
      dockerfile: dockerfiles/kitchen.Dockerfile
    image: kitchen:latest
    container_name: kitchen-container
    ports:
      - 80:80
      - 81:81
    volumes:
      - $HOME/.aws:/root/.aws
    command: bash -c "
      python -m head_chef.head_chef
      & hypercorn server.server:app --bind 0.0.0.0:81
      & streamlit run window_display/custom_display.py --server.port 80
      "

  test:
    build:
      context: .
      dockerfile: dockerfiles/kitchen.Dockerfile
    image: kitchen:latest
    container_name: test-kitchen
    volumes:
      - $HOME/.aws:/root/.aws
    command: python -m head_chef.head_chef
