version: "3.8"

services:

  kitchen:
    build:
      context: .
      dockerfile: dockerfiles/kitchen.Dockerfile
    image: kitchen:latest
    container_name: kitchen-container
    ports:
      - 80:80
      - 81:81
      - 8443:8443
      - 8888:8888
    volumes:
      - $HOME/.aws:/root/.aws
    command: bash -c "
      jupyter lab --ip=0.0.0.0 --allow-root --no-browser
      & hypercorn server.server:app --bind 0.0.0.0:81
      & streamlit run window_display/custom_display.py --server.port 80
      & code-server --bind-addr 0.0.0.0:8443 --auth none
      "

  test:
    build:
      context: .
      dockerfile: dockerfiles/kitchen.Dockerfile
    image: kitchen:latest
    container_name: test-kitchen
    volumes:
      - $HOME/.aws:/root/.aws
    command: python -m head_chef.head_chef
